name: Deploy on DockerHub

on:
  push:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Test
        run: mvn -B test
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify
#
#  sonar:
#    name: Test - SonarCloud Scan
#    runs-on: ubuntu-18.04
#
#    steps:
#      - uses: actions/checkout@v1
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11.0.4
#      - name: SonarCloud Scan
#        run: mvn -B clean verify -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#  artifact:
#    name: Publish - GitHub Packages
#    runs-on: ubuntu-18.04
#    needs: [test]
#
#    steps:
#      - uses: actions/checkout@v1
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11.0.4
#      - name: Publish artifact on GitHub Packages
#        run: mvn -B clean deploy -DskipTests
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dockerHub:
    name: Publish on Docker Hub
    runs-on: ubuntu-18.04
    needs: [test]
    env:
      REPO: teixeira963

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Maven Package
        run: mvn -B clean package -DskipTests

      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKERHUB_USER }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.3.0
        with:
          context: .
          file: ./Dockerfile
          tags: |
            teixeira963/github-api:latest
            teixeira963/github-api:${{ github.run_number }}
          push: true

  notifySlack:
    runs-on: ubuntu-18.04
    needs: [dockerHub]

    steps:
      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: abinoda/slack-action@master
        with:
          args: '{\"channel\":\"C01VA672CJH\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Successfully deployed on Heroku!\"}}]}'
